# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-05 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='rt_request',
            field=models.TextField(blank=True, default='', verbose_name='RT request text'),
        ),
        migrations.AddField(
            model_name='process',
            name='rt_ticket',
            field=models.IntegerField(null=True, verbose_name='RT request ticket'),
        ),
    ]
