# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20170805_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='rt_ticket',
            field=models.IntegerField(blank=True, null=True, verbose_name='RT request ticket'),
        ),
    ]
