# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20170805_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='fpr',
            field=models.ForeignKey(help_text='Fingerprint used to verify the statement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.Fingerprint'),
        ),
    ]
