# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 18:22
from __future__ import unicode_literals
from django.db import migrations
from django.utils.timezone import now


def add_process_started(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Process = apps.get_model('process', 'Process')
    for process in Process.objects.all():
        try:
            process.started = process.log.order_by("logdate")[0].logdate
        except IndexError:
            process.started = now()
        process.save()


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_process_started'),
    ]

    operations = [
        migrations.RunPython(add_process_started),
    ]
