# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20170812_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='started',
            field=models.DateTimeField(auto_now_add=True, verbose_name='process started'),
        ),
    ]
