# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 08:48
from __future__ import unicode_literals
from django.db import migrations


def fill_process_closed_by(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model("backend", "Person")
    try:
        robot = Person.objects.get(username="__housekeeping__")
    except Person.DoesNotExist:
        robot = None
    Process = apps.get_model('process', 'Process')
    for process in Process.objects.all():
        if process.closed_time is None: continue
        if process.closed_by is not None: continue
        process.closed_by = robot or process.approved_by or process.frozen_by or process.person
        process.save()


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_process_closed'),
    ]

    operations = [
        migrations.RunPython(fill_process_closed_by),
    ]
