# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_fill_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='hide_until',
            field=models.DateTimeField(blank=True, help_text='Hide this process from the AM dashboard until the given date', null=True),
        ),
    ]
