# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20170519_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='last_upload',
            field=models.DateField(blank=True, help_text='date of the last ftp-master upload done with this key', null=True),
        ),
    ]
