# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_fingerprint_last_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_vote',
            field=models.DateField(blank=True, help_text='date of the last vote done with this uid', null=True),
        ),
    ]
